main: ftsos.skywars.Skywars
version: 0.1.0
name: Skywars
commands:
  skywars:
    description: A normal Skywars Command /sw help for help
    aliases: sw
  swadminkit:
      description: an admin kitsw command
depend:
  - WorldEdit
