main: ftsos.skywars.Skywars
version: 0.0.1
name: Skywars
commands:
  skywars:
    description: A normal Skywars Command /sw help for help
    aliases: sw
  swadminkit:
      description: an admin kitsw command
  addcagecommand:
    description: awa
depend:
  - WorldEdit